kind: pipeline
name: testing

trigger:
  branch:
    include:
      - main
      - develop
  event:
    include:
      - push
      - pull_request

image_pull_secrets:
  - dockerconfig

steps:
  - name: restore-cache
    image: meltwater/drone-cache:dev
    pull: true
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: cache_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_aws_secret_access_key
    settings:
      restore: true
      bucket: kolaente.dev-drone-dependency-cache
      endpoint: https://s3.fr-par.scw.cloud
      region: fr-par
      path_style: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "yarn.lock" }}_{{ checksum "composer.lock" }}_{{ arch }}_{{ os }}'
      mount:
        - '.cache'

  - name: dependencies
    image: composer:2
    pull: true
    environment:
      COMPOSER_HOME: .cache/composer
    commands:
      - composer install --optimize-autoloader --ignore-platform-req=php --ignore-platform-req=ext-bcmath --ignore-platform-req=ext-gd
    depends_on:
      - restore-cache

  - name: dependencies-frontend
    image: node:22
    pull: true
    environment:
      YARN_CACHE_FOLDER: .cache/yarn/
    commands:
      - yarn install
    depends_on:
      - restore-cache

  - name: rebuild-cache
    image: meltwater/drone-cache:dev
    pull: true
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: cache_aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: cache_aws_secret_access_key
    settings:
      rebuild: true
      bucket: kolaente.dev-drone-dependency-cache
      endpoint: https://s3.fr-par.scw.cloud
      region: fr-par
      path_style: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "yarn.lock" }}_{{ checksum "composer.lock" }}_{{ arch }}_{{ os }}'
      mount:
        - '.cache'
    depends_on:
      - dependencies

  - name: build-frontend
    image: node:22
    pull: true
    environment:
      YARN_CACHE_FOLDER: .cache/yarn/
    commands:
      - yarn prod
    depends_on:
      - dependencies-frontend

  - name: test
    image: kolaente/laravel:8.2-octane-dev
    pull: true
    environment:
      DB_CONNECTION: sqlite
      DB_DATABASE: /drone/src/database.sqlite
      DB_FOREIGN_KEYS: true
    commands:
      - cp .env.example .env
      - php artisan key:generate
      - ./vendor/bin/phpunit
    depends_on:
      - dependencies
---
kind: pipeline
name: docker

depends_on:
  - testing

trigger:
  ref:
    - refs/heads/main
    - "refs/tags/**"

image_pull_secrets:
  - dockerconfig

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: docker-prod
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: hub.kolaente.de/wobsites/life-v2
      registry: hub.kolaente.de
      tags: latest
    depends_on: [ fetch-tags ]

---
kind: pipeline
name: docker-unstable

depends_on:
  - testing

trigger:
  ref:
    - refs/heads/develop

image_pull_secrets:
  - dockerconfig

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: docker-unstable
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: hub.kolaente.de/wobsites/life-v2
      registry: hub.kolaente.de
      tags: unstable
    depends_on: [ fetch-tags ]
