FROM ghcr.io/kolaente/laravel-docker:8.3-octane-frankenphp

RUN apt-get update && apt-get install -y mariadb-client && \
  docker-php-ext-install pdo pdo_mysql && \
  rm -rf /var/lib/apt/lists/*

# Octane watcher
ENV NODE_MAJOR=22
RUN mkdir -p /etc/apt/keyrings && \
   curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
   echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
   apt-get update && apt-get install nodejs -y && \
   npm -g install chokidar

CMD ["php", "-d", "variables_order=EGPCS", "/app/artisan", "octane:frankenphp", "--workers=1", "--port", "80", "--host", "0.0.0.0"]
