FROM php:8.0-apache

ENV APACHE_DOCUMENT_ROOT /var/www/public

COPY apache.conf /etc/apache2/sites-available/000-default.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf && \
sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf && \
sed -ri -e 's!LogFormat\ "\%h\ \%l\ \%u\ \%t!LogFormat\ "\%h\ \%l\ \%u\ \%t\ \%D!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf && \
echo "upload_max_filesize = 2G; " > /usr/local/etc/php/conf.d/upload.ini && \
echo "post_max_size = 2500M;" >> /usr/local/etc/php/conf.d/upload.ini && \
echo "date.timezone = \"Europe/Berlin\"" >> /usr/local/etc/php/conf.d/timezone.ini && \
echo 'memory_limit = 2G' >> /usr/local/etc/php/conf.d/max_memory.ini
RUN apt-get update && \
  apt-get install -y \
    git \
    curl libcurl3-dev \
    mariadb-client \
    libpng-dev libwebp-dev libjpeg62-turbo-dev libfreetype6-dev libpng-dev \
    libxpm-dev \
    zip libzip-dev \
    gnupg2 \
    sudo && \
  docker-php-ext-configure curl && \
  docker-php-ext-install mysqli curl exif && \
  docker-php-ext-configure zip && \
  docker-php-ext-install zip && \
  docker-php-ext-configure gd && \
  docker-php-ext-install gd && \
  docker-php-ext-install pdo pdo_mysql && \
  a2enmod rewrite

RUN pecl install xdebug && \
  docker-php-ext-enable xdebug && \
  echo 'zend_extension = /usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so' >> /usr/local/etc/php/php.ini && \
  touch /usr/local/etc/php/conf.d/xdebug.ini; \
  echo xdebug.mode=debug >> /usr/local/etc/php/conf.d/xdebug.ini; \
  echo xdebug.discover_client_host=true >> /usr/local/etc/php/conf.d/xdebug.ini

WORKDIR /var/www

ADD setup.sh /usr/local/bin/setup
ADD run.sh /
CMD /run.sh
